export const colorOptions = [
  { color: '#FF5252', backgroundColor: '#FFEEEE' },
  { color: '#FF4081', backgroundColor: '#FFEEF5' },
  { color: '#E040FB', backgroundColor: '#F9E6FF' },
  { color: '#7C4DFF', backgroundColor: '#F0EBFF' },
  { color: '#536DFE', backgroundColor: '#EBEEFF' },
  { color: '#448AFF', backgroundColor: '#EAF4FF' },
  { color: '#40C4FF', backgroundColor: '#E6F9FF' },
  { color: '#18FFFF', backgroundColor: '#E6FFFF' },
  { color: '#64FFDA', backgroundColor: '#EAFFFA' },
  { color: '#69F0AE', backgroundColor: '#EAFFF5' },
  { color: '#B2FF59', backgroundColor: '#F6FFEA' },
  { color: '#EEFF41', backgroundColor: '#FBFFE6' },
  { color: '#FFFF00', backgroundColor: '#FFFFEA' },
  { color: '#FFD740', backgroundColor: '#FFF8E6' },
  { color: '#FFAB40', backgroundColor: '#FFF5EA' },
  { color: '#FFA500', backgroundColor: '#FFF3E0' },
];
